[book]
authors = ["Sebastian Nagel"]
language = "en"
multilingual = false
src = "src"
title = "Cardano Blueprint"

[build]
build-dir = "out"

[preprocessor]

[preprocessor.alerts]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
